version: '3.8'

services:
  bitcoind:
    image: lncm/bitcoind:v22.0@sha256:37a1adb29b3abc9f972f0d981f45e41e5fca2e22816a023faa9fdc0084aa4507
    container_name: bitcoind
    user: root
    command: -regtest -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcauth=user:63cf03615adebaa9356591f95b07ec7b$$920588e53f94798bda636acac1b6a77e10e3ee7fe57e414d62f3ee9e580cd27a -fallbackfee=0.0001 -zmqpubrawblock=tcp://0.0.0.0:28332 -zmqpubrawtx=tcp://0.0.0.0:28333
    ports:
      - "18443:18443"
      - "28332:28332"
      - "28333:28333"
    volumes:
      - bitcoin_data:/root/.bitcoin

  lndnode:
    image: lightninglabs/lndinit:v0.1.21-beta-lnd-v0.18.0-beta
    container_name: lndnode
    user: root
    hostname: lnd
    entrypoint: 
      - sh
      - -c
      - |
        if [[ ! -f /data/seed.txt ]]; then
          lndinit gen-seed > /data/seed.txt
        fi
        if [[ ! -f /data/walletpassword.txt ]]; then
          lndinit gen-password > /data/walletpassword.txt
        fi
        lndinit -v init-wallet \
          --secret-source=file \
          --file.seed=/data/seed.txt \
          --file.wallet-password=/data/walletpassword.txt \
          --init-file.output-wallet-dir=/root/.lnd/data/chain/bitcoin/regtest \
          --init-file.validate-password
        mkdir -p /data/.lnd
        if [ ! -f "/data/.lnd/umbrel-lnd.conf" ]; then
          touch "/data/.lnd/umbrel-lnd.conf"
        fi
        lnd --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoind --bitcoind.rpcuser=user --bitcoind.rpcpass=pass --bitcoind.zmqpubrawblock=tcp://bitcoind:28332 --bitcoind.zmqpubrawtx=tcp://bitcoind:28333 --configfile=/data/.lnd/umbrel-lnd.conf --wallet-unlock-password-file=/data/walletpassword.txt --wallet-unlock-allow-create
    ports:
      - "9735:9735"
      - "10009:10009"
      - "8080:8080"
    volumes:
      - lndnode-data:/data/.lnd
    restart: unless-stopped
    environment:
      HOME: /data
    command: [ '/init-wallet-k8s.sh' ]
    depends_on:
      - bitcoind

  cln:
    image: elementsproject/lightningd:v25.05
    container_name: cln
    user: root
    entrypoint:
      - sh 
      - -c
      - |
        # Install NWC plugin
        if [ ! -f "/usr/local/libexec/c-lightning/plugins/cln-nip47" ]; then
          apt-get update && apt-get install -y wget
          cd /tmp
          wget -O nwc.tar.gz https://github.com/daywalker90/cln-nip47/releases/download/v0.1.3/cln-nip47-v0.1.3-x86_64-linux-gnu.tar.gz
          tar xzf nwc.tar.gz
          chmod +x cln-nip47
          mv cln-nip47 /usr/local/libexec/c-lightning/plugins/cln-nip47
        fi
        lightningd \
          --network=regtest \
          --bitcoin-rpcconnect=bitcoind \
          --bitcoin-rpcport=18443 \
          --bitcoin-rpcuser=user \
          --bitcoin-rpcpassword=pass \
          --addr=cln:9835 \
          --grpc-port=9996 \
          --plugin=/usr/local/libexec/c-lightning/plugins/cln-nip47 \
          --nip47-relays=wss://relay.damus.io
    ports:
      - "9835:9835"
      - "9996:9996"
    volumes:
      - cln-data:/root/.lightning:rw
      - /cln-socket:/root/.lightning/regtest
    depends_on:
      - bitcoind

volumes:
  bitcoin_data:
  lndnode-data:
  cln-data:
