name: Unused Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cargo-machete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-machete
        run: cargo install cargo-machete --locked --version 0.9.2

      - name: Run cargo machete
        run: cargo machete
